#pragma config(Motor,  port2,           rDrive,        tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port4,           bottomHabitat, tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armGrip,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           topHabitat,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           lDrive,        tmotorServoContinuousRotation, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void arcadeDrive(){
	setMotor(lDrive, vexRT[Ch3] + vexRT[Ch4]);
	setMotor(rDrive, vexRT[Ch3] - vexRT[Ch4]);
}

void tankDrive(){
	setMotor(lDrive, vexRT[Ch3]);
	setMotor(rDrive, vexRT[Ch2]);
}

void inverseArcade(){
	setMotor(lDrive, -(vexRT[Ch3] + vexRT[Ch4]));
	setMotor(rDrive, -(vexRT[Ch3] - vexRT[Ch4]));
}

void inverseTank(){
	setMotor(lDrive, -(vexRT[Ch3]));
	setMotor(rDrive, -(vexRT[Ch2]));
}

bool changeDrive = true;
bool driveArcade = true;
bool driveInverse = true;
bool changeDrive2 = true;
void customArcade(bool toggle, bool toggle2){
	if (toggle && changeDrive) {
		driveArcade = !driveArcade;
		changeDrive = false;
	}
	if (!toggle && !changeDrive) {
		changeDrive = true;
	}
	if (toggle2 && changeDrive2) {
		driveInverse = !driveInverse;
		changeDrive2 = false;
	}
	if (!toggle2 && !changeDrive2) {
		changeDrive2 = true;
	}
	if (driveArcade && driveInverse) {
		arcadeDrive();
	}
	else if (driveArcade && !driveInverse){
		inverseArcade();
	}
	if (!driveArcade && driveInverse) {
		tankDrive();
	}
	else if (!driveArcade && !driveInverse){
		inverseTank();
	}
}

void motorPosControl(float motor, bool up, bool down) {
	if(up) {
		setMotor(motor, 127);
		}	else if(down){
		setMotor(motor, -127);
		}	else {
		setMotor(motor, 0);
	}
}

void halfMotor(float motor, bool up, bool down) {
	if(up) {
		setMotor(motor, 127/2);
		}	else if(down){
		setMotor(motor, -127/2);
		}	/*else {
		setMotor(motor, 0);
	}*/
}

void servoControl(float motor, bool up, bool down){
	if (up){
		setMotor(motor, 120);
	}
	if (down){
		setMotor(motor, -120);
	}
}

task main(){
	while (true){
		customArcade(vexRT[Btn8D], vexRT[Btn7R]);		//move wheels using joysticks

		servoControl(armGrip, vexRT[Btn8U], vexRT[Btn8D]);	//move arm grabber using buttons

		//motorPosControl(elevator, vexRT[Btn6D], vexRT[Btn6U]); 	//move elevator using buttons

		//servoControl(coreGrip, vexRT[Btn8L], vexRT[Btn8R]); 	//move core grip using buttons

		//servoControl(topHabitat, vexRT[Btn7U], vexRT[Btn7D]);

		//servoControl(bottomHabitat, vexRT[Btn7U], vexRT[Btn7D]);

		motorPosControl(arm, vexRT[Btn5U], vexRT[Btn5D]);		//move arm using buttons
		halfMotor(arm, vexRT[Btn6U], vexRT[Btn6D]);
	}
}
